config/routes.rb
Rails.application.routes.draw do

  root 'home#index'
  get '/aleatorio'   => 'home#aleatorio',   as: 'aleatorio'
  get '/gasto_total' => 'home#gasto_total', as: 'gasto_total', defaults: { format: :json }
  get '/sitemap.xml' => 'home#sitemap',     as: 'sitemap', defaults: { format: :xml }

  resources :deputados do
  	resources :despesas, :module => :deputados
  end
end

app/models/deputado.rb
class Deputado < ActiveRecord::Base

  has_many :despesas

  update_index('deputados#deputado') { self }

  scope :com_total_despesas, -> {
     joins("LEFT JOIN despesas ON despesas.deputado_id = deputados.id")
    .select('deputados.*', 'sum(despesas.valor_liquido) as total_despesas')
    .group('deputados.nome')
  }

  scope :partidos, -> {
    select('distinct(partido), count(*) as quantidade')
    .group('deputados.partido')
    .map do |deputado|
      {
        :nome       => deputado.partido,
        :quantidade => deputado.quantidade
      }
   end
  }

  scope :aleatorios,       -> { com_total_despesas.order('RAND()')              }
  scope :com_despesas,     -> { com_total_despesas.includes(:despesas)          }
  scope :maiores_despesas, -> { com_total_despesas.order('total_despesas desc') }
  scope :top_tres,         -> { aleatorios.limit(3)                             }


  def self.buscar(query, attrs = {})
    fields = ['nome', 'partido', 'nome_parlamentar', 'matricula', 'email', 'uf', 'despesas.*']
    deputados_ids = DeputadosIndex.query(multi_match: { query: query, fields: fields }).map { |d| d.id }

    # Busca por ID os registros encontrados pela busca
    self.maiores_despesas.where(id: deputados_ids)
  end


  def self.todos(query, current_page, per_page = 10)
    deputados = query.blank? ? self.maiores_despesas : self.buscar(query)
    deputados.paginate(:page => current_page, :per_page => per_page)
  end


  def data_ultima_atualizacao
    !despesas.empty? ? despesas.mais_novos.first.updated_at : updated_at
  end


  def slug
    nome_parlamentar.parameterize
  end


  def to_param
    "#{id}-#{slug}"
  end
end

app/models/despesa.rb
class Despesa < ActiveRecord::Base

  belongs_to :deputado

  scope :total_gasto,        -> { sum(:valor_liquido) }
  scope :mais_novos,         -> { order('data_emissao desc') }
  scope :por_classificacao,  -> (classificacao) { where(:descricao => classificacao) }

  scope :classificacoes, -> {
    select("distinct(descricao)").map { |classificacao| classificacao.descricao }
  }

  scope :totais_por_descricao, -> {
    select("descricao,sum(valor_liquido) as total_liquido,sum(valor_documento) as total")
    .group("descricao")
    .map do |despesa|
      {
        :descricao     => despesa.descricao,
        :total_liquido => despesa.total_liquido,
        :total         => despesa.total
      }
    end
  }

  def self.todos(query, current_page, per_page = 20)
    mais_novos.paginate(:page => current_page, :per_page => per_page)
  end

  def self.por_filtro(filtro)
    mais_novos.where(filtro)
  end


  # retorna gastos anuais mes a mes
  def self.mensal(deputado_id = nil)
    default = Hash[(1..12).collect {|n| [n, nil]}]

    total = (deputado_id.nil? ? Despesa : Despesa.where(deputado_id: deputado_id))
              .group([:num_ano, :num_mes]).having('num_ano > 0').total_gasto

    # output = [{ano1 => {mes1 => valor, mes2 => valor, ...}}, {ano2 => {mes1 => valor, ...}}]
    total.group_by{|key, value| key[0] }.map do |ano, valores|
      { ano => default.merge(Hash[valores.collect {|mes, valor| [mes[1], valor.to_f]}]) }
    end
  end

  def self.total_of_cost
    self.sum(:valor_liquido)
  end

  # retorna gastos anuais
  def self.anual
    Despesa.group(:num_ano).having('num_ano > 0').total_gasto
  end
end

app/models/versao_web_service.rb
require 'open-uri'

class VersaoWebService < ActiveRecord::Base
  def self.atualizado?(url)
    file     = open(url)
    sha1hash = Digest::SHA1.file(file).to_s

    !self.exists?(:url => url, :sha1hash => sha1hash)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deputados/despesas_controller.rb
class Deputados::DespesasController < ApplicationController
  def index
    @deputado = Deputado.com_total_despesas.find(params[:deputado_id])
    @despesas = @deputado.despesas.por_filtro(filter_params).paginate(page: params[:page], per_page: 20)

    @opengraph = {
      title:      'Deputado: ' + @deputado.nome.titleize,
      type:       'website',
      url:        url_for(:only_path => false, :overwrite_params => nil),
      image:      @deputado.url_foto,
      site_name: 'Peba'
    }
  end

  def filter_params
    filtro = Hash.new
    filtro[:num_ano]   = params[:num_ano]   unless params[:num_ano].blank?
    filtro[:num_mes]   = params[:num_mes]   unless params[:num_mes].blank?
    filtro[:descricao] = params[:descricao] unless params[:descricao].blank?

    return filtro
  end
end

app/controllers/deputados_controller.rb
class DeputadosController < ApplicationController
  def index
     @deputados = Deputado.todos(params[:q], params[:page])
  end

  def show
    @deputado = Deputado.com_total_despesas.find(params[:id])
    @despesas = @deputado.despesas.todos(params[:q], params[:page])

    @page_info = {
      title: 'Deputado: ' + @deputado.nome.titleize
    }

    @opengraph = {
      title:      'Deputado: ' + @deputado.nome.titleize,
      type:       'website',
      url:        url_for(:only_path => false, :overwrite_params => nil),
      image:      @deputado.url_foto,
      site_name: 'Peba'
    }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @page_info = {
      title: 'Indexador de Dados Públicos',
      description:  'O Peba é um sistema que indexa em fonte única informações relacionadas às despesas de vários entidades ' <<
                    'governamentais com suporte para filtros e buscas avançadas.'
    }
    @opengraph = {
      title:        'Peba - Indexador de Dados Públicos',
      type:         'website',
      url:          root_url,
      image:        view_context.image_url('peba_logo_og.png'),
      site_name:    'Peba',
      description:  'O Peba é um sistema que indexa em fonte única informações relacionadas às despesas de vários entidades ' <<
                    'governamentais com suporte para filtros e buscas avançadas.'
    }
  end


  def gasto_total
    @gastos = Despesa.mensal params[:deputado_id]
  end


  def aleatorio
    deputado = Deputado.aleatorios.first
    redirect_to deputado_path deputado
  end

  def sitemap
    @host      = 'http://peba.teresinahc.org/'
    @politicos = Deputado.all

    respond_to do |format|
      format.xml { render 'sitemap/index', layout: nil }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon(name, options = {})
    default_options = { class: ['glyphicon', "glyphicon-#{name}"], 'aria-hidden' => 'true' }
    options         = default_options.merge(options)

    content_tag(:span, nil, options).html_safe
  end

  def app_description
    'O Peba é um sistema que indexa em fonte única informações relacionadas às despesas de vários entidades ' <<
    'governamentais com suporte para filtros e buscas avançadas.'
  end
end

app/helpers/deputados_helper.rb
module DeputadosHelper
  def detalhe_deputado_url(id_cadastro)
    "http://www.camara.gov.br/internet/deputado/Dep_Detalhe.asp?id=#{id_cadastro}"
  end

  def cota_deputado_url(id_cadastro)
    "http://www.camara.gov.br/cota-parlamentar/consulta-cota-parlamentar?ideDeputado=#{id_cadastro}"
  end
end

app/helpers/despesas_helper.rb
module DespesasHelper

  def sum_partial_of_document_value(cost)
    cost.inject(0) { |sum, despesa| sum + despesa.valor_documento.to_f}
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper

  def build_receipt_url(external_politic_id, year, external_document_id)
    link = "http://www.camara.leg.br/cota-parlamentar/documentos/publ/"
    link << external_politic_id.to_s + '/'
    link << year.to_s + '/'
    link << external_document_id.to_s + '.pdf'
  end

end

app/views/deputados/_deputado.html.erb
<div class='jumbotron'>
  <div class="container" >
    <div class="info">
      <div class='text-center'>
        <div class="circle center">
          <img src="<%= deputado.url_foto %>" alt="">
        </div>

        <h1><%= deputado.nome.titleize_name %></h1>

        <h3 class='situacao-partido-estado'>
          <%= "#{deputado.partido}, #{deputado.uf} - #{deputado.situacao_candidatura}" %>
        </h3>

        <div class='contato'>
          <span class='email'>
            <%= icon(:envelope) %> <%= mail_to(deputado.email) %>
          </span>
        </div>

        <div id="social" >
          <%= render(
              partial: 'partials/social',
              locals: { url: @opengraph[:url], description: @opengraph[:description] }
            )
          %>
        </div>
      </div>
    </div>
  </div>

  <div class='estatisticas'>
    <div class='container'>
      <div class='text-center'>
        <ul>
          <% unless deputado.total_despesas.nil? %>
            <li>
              <p><%= number_to_currency(deputado.total_despesas) %></p>
              <span>gastos (a partir de 01/01/2015)</span>
            </li>
          <% end %>

          <li>
            <p><%= number_with_delimiter(deputado.total_votos) %></p>
            <span>votos</span>
          </li>

          <li>
            <p><%= number_to_percentage(deputado.porcentagem_votos, precision: 2) %></p>
            <span>votos válidos</span>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/deputados/despesas/index.html.erb
<div id="politico">

  <%= render partial: 'deputados/deputado', locals: { deputado: @deputado } %>

  <div id="despesas" class="container" >
    <div class="col-lg-12" >
      <h3 class='subtitle'><%= t '.subtitle' %></h3>

      <div id="filter" class="row" >
        <%= form_tag(deputado_despesas_path(@deputado.id), class: 'inline-form', method: 'get') do |f| %>
          <div class="col-lg-3" >
            <div class="form-group" >
              <label for="descricao"><%= Despesa.human_attribute_name(:classificacao) %></label>
              <%= select_tag(:descricao,  options_for_select(@deputado.despesas.classificacoes, selected: params[:descricao]), include_blank: t('options.all'), class: 'form-control', onchange: 'this.form.submit()') %>
            </div>
          </div>
          <div class="col-lg-2" >
            <div class="form-group" >
              <label for="date_year"><%= Despesa.human_attribute_name(:year) %></label>
              <%= select_year(params[:num_ano].to_i, { start_year: 2015, end_year: Date.current.year, prompt: t('options.all') }, name: 'num_ano', class: 'form-control', onchange: 'this.form.submit()') %>
            </div>
          </div>
          <div class="col-lg-2" >
            <div class="form-group" >
              <label for="date_month"><%= Despesa.human_attribute_name(:month) %></label>
              <%= select_month(params[:num_mes].to_i, { include_blank: t('options.all') }, class: 'form-control', onchange: 'this.form.submit()', name: 'num_mes') %>
            </div>
          </div>
        <% end %>
      </div>

      <div id="update-info text-right" >
        <%= t '.last_update_at' %>: <%= l @deputado.data_ultima_atualizacao, format: :short %>
      </div>
      <div id="update-info text-right" >
        <%= t '.sum_of_expenses_of_current_filter' %>: <b><%= number_to_currency(@despesas.total_of_cost) %></b>
      </div>

      <table class="table table-hover">
        <thead>
          <tr>
            <th width='100'><%= Despesa.human_attribute_name :data_emissao %></th>
            <th><%= Despesa.human_attribute_name :beneficiario %></th>
            <th><%= Despesa.human_attribute_name :cpf_cnpj %></th>
            <th><%= Despesa.human_attribute_name :valor_liquido %><small>*</small></th>
            <th><%= Despesa.human_attribute_name :valor_glosa %><small>**</small></th>
            <th><%= Despesa.human_attribute_name :valor_documento %><small>***</small></th>
            <th align="center"><%= Despesa.human_attribute_name :receipt %></th>
          </tr>
        </thead>
        <tbody>
          <% @despesas.each do |despesa| %>
            <tr>
              <td><%= despesa.data_emissao.nil? ? '-' : despesa.data_emissao.to_time.strftime('%d/%m/%Y') %></td>
              <td><%= despesa.beneficiario %></td>
              <td><%= despesa.cpf_cnpj.empty? ? '-' :  despesa.cpf_cnpj %></td>
              <td align="right" ><%= number_to_currency(despesa.valor_liquido) %></td>
              <td align="right" ><%= number_to_currency(despesa.valor_glosa) %></td>
              <td align="right" ><%= number_to_currency(despesa.valor_documento) %></td>
              <td align="center" >
                <a href="<%= build_receipt(despesa.nu_deputado_id, despesa.num_ano, despesa.ide_documento) %>" target="_blank" >
                  <span class="glyphicon glyphicon-circle-arrow-down" ></span> <%= t 'actions.view' %>
                </a>
              </td>
            </tr>
          <% end %>
          <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td align="right"><strong><%= t '.subtotal' %>:</strong></td>
            <td align="right"><strong><%= number_to_currency(sum_partial_of_document_value(@despesas)) %></strong></td>
            <td></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <div class="paginator-wrapper" >
    <%= will_paginate @despesas, renderer: BootstrapPagination::Rails, params: {:anchor => 'despesas'} %>

    <p><%= link_to icon('chevron-left') << "Voltar para Versão resumida", deputado_path(@deputado) %></p>
  </div>

  <div class="container fonte-dados">
    <ul class="list-unstyled" >
      <li> <span class='label'>Fonte dos dados:</span>
        <ul>
          <li><%= link_to(nil, cota_deputado_url(@deputado.id_cadastro), target: '_blank') %></li>
          <li><%= link_to(nil, 'http://www.tse.jus.br/eleicoes/estatisticas/estatisticas-candidaturas-2014', target: '_blank') %></li>
        </ul>
      </li>
    </ul>

    <p class="small">* <em>Valor líquido</em> é aquele que não possui descontos ou encargos.</p>
    <p class="small">** <em>Valor Glosado</em> é toda cobrança efetuada que não coincide com os acordos e regras firmadas entre o serviço contratado e a empresa contratante.</p>
    <p class="small">*** <em>Valor do documento</em> é o valor líquido acrescido do valor glosado.</p>
  </div>
</div>

app/views/deputados/index.html.erb
<%= render partial: 'partials/search_cover' %>

<div id="search-page">

  <div class='container'>

    <div id="info" class="col-lg-12" >
      <h4 class="lead">
        <% if(@deputados.total_entries == 0) %>
          Nenhum político foi encontrado para a pesquisa <b><%= params[:q] %></b>
        <% else %>
          <b><%= @deputados.total_entries %></b>
          <%= 'político'.pluralize(@deputados.total_entries) %>
          <%= 'foi'.pluralize(@deputados.total_entries) %>
          <%= 'encontrado'.pluralize(@deputados.total_entries) %>
          <% if(params[:q].present? and !params[:q].empty?) %>
            para a pesquisa <b><%= params[:q] %></b>
          <% end %>
        <% end %>
      </h4>
    </div>

    <div class="col-lg-12">
      <div class="paginator-wrapper">
        <%= will_paginate @deputados, renderer: BootstrapPagination::Rails %>
      </div>
    </div>

    <section id="search-results" class="col-lg-8 col-lg-offset-2">
      <% @deputados.each do |deputado| %>
        <a class="row search-result" href="<%= deputado_path deputado %>">
          <div class="col-lg-3" >
            <div class="circle" >
              <%= image_tag deputado.url_foto  %>
            </div>
          </div>
          <div class="col-lg-5" >
            <h3 class="name" ><%= deputado.nome_parlamentar %></h3>
            <ul class="list-unstyled" >
              <li>Partido: <%= deputado.partido %></li>
              <li>Estado: <%= deputado.uf %></li>
              <% unless deputado.situacao_candidatura.nil? %>
                <li>Total de votos: <%= number_with_delimiter(deputado.total_votos) %></li>
              <% end %>
              <li><b>Despesas: <%= number_to_currency(deputado.total_despesas) %></b></li>
            </ul>
          </div>
          <div class="col-lg-4" >
                <span class="more-infos btn btn-primary" >
                  <i class="glyphicon glyphicon-search"></i> Ver despesas
                </span>
          </div>
        </a>
      <% end %>
    </section>

    <div class="col-lg-12">
      <div class="paginator-wrapper">
        <%= will_paginate @deputados, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/deputados/show.html.erb
<div id="politico">

  <%= render @deputado %>

  <div id="despesas" class="container" >
    <small id="update-info text-right" >
      Última atualização em: <%= l @deputado.data_ultima_atualizacao, format: :short %>
    </small>

    <div class='col-gl-12' >
      <section id='graficos'>
        <h3 class='subtitle'>Gastos Anuais Registrados</h3>
        <div class='grafico' id='gasto-total-por-mes' data-url='<%= gasto_total_path(deputado_id: @deputado.id) %>'></div>
      </section>
    </div>

    <div class="col-lg-12" >
      <h3 class='subtitle'>Classificações de Despesas</h3>

      <table class="table table-hover">
        <tr>
          <th>Descrição</th>
          <th style="text-align:right" >Valor líquido</th>
          <th style="text-align:right" >Valor total</th>
        </tr>
        <% @despesas.totais_por_descricao.each do |tipo| %>
          <tr>
            <td><%= tipo[:descricao] %></td>
            <td align="right" ><%= number_to_currency(tipo[:total_liquido]) %></td>
            <td align="right" ><%= number_to_currency(tipo[:total]) %>      </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="paginator-wrapper" >
    <%= link_to "Ver detalhes das despesas", deputado_despesas_path(@deputado, anchor: 'despesas'), :class => "btn btn-primary btn-yellow" %>
  </div>

  <div class="container fonte-dados">
    <ul class="list-unstyled" >
      <li> <span class='label'>Fonte dos dados:</span>
        <ul>
          <li><%= link_to(nil, detalhe_deputado_url(@deputado.id_cadastro), target: '_blank') %></li>
          <li><%= link_to(nil, 'http://www.tse.jus.br/eleicoes/estatisticas/estatisticas-candidaturas-2014', target: '_blank') %></li>
        </ul>
      </li>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<%= render partial: 'partials/search_cover' %>

<div class='container'>

  <div class='row' >
    <!-- <div class='col-gl-12' >
      <div id='video-wrapper' >
        <iframe width='502' height='282' src='https://www.youtube.com/embed/96meq3ACiCk' frameborder='0' allowfullscreen></iframe>
      </div>
    </div> -->

    <div class='col-gl-12' >
      <section id='graficos'>
        <h3 class='subtitle'>Gastos Anuais Registrados</h3>
        <div class='grafico' id='gasto-total-por-mes' data-url='<%= gasto_total_path %>'></div>
      </section>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <% if defined? @opengraph %>
    <%= render 'partials/opengraph_tags' %>
  <% end %>

  <% if !defined? @page_info[:title] %>
    <title>Peba - Indexador de dados públicos</title>
  <% else %>
    <title>Peba - <%= @page_info[:title] %></title>
  <% end %>

  <% if defined? @page_info[:description] %>
    <meta name="description" content="<%= @page_info[:description] %>" >
  <% else %>
    <meta name="description" content="<%= app_description %>" >
  <% end %>

  <link rel="icon" type="image/png" href="<%= image_path('favicon.png') %>" />
  <%= stylesheet_link_tag :application, media: 'all'%>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render partial: 'partials/navbar' %>
  <%= yield %>

  <%= render partial: 'partials/footer' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script type="text/javascript">window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));</script>
  <script type="text/javascript">if(typeof wabtn4fg==="undefined"){wabtn4fg=1;h=document.head||document.getElementsByTagName("head")[0],s=document.createElement("script");s.type="text/javascript";s.src="<%= root_url + asset_path('whatsapp-button.js') %>";h.appendChild(s);}</script>
</body>
</html>

app/views/partials/_common_links.html.erb
<% unless(params[:controller] == 'home') %>
  <li><%= link_to 'Início', root_path, title: 'Ir para a página inicial', accesskey: 'i' %></li>
<% end %>
<li><%= link_to 'Sobre o projeto', 'http://teresinahc.org/wiki/index.php/Projetos:Peba',  target: '_blank', title: 'Página sobre o projeto (Abre em uma nova janela)' %></li>
<li><%= link_to 'Teresina Hacker Clube', 'http://teresinahc.org', target: '_blank', title: 'Página do Teresina Hacker Clube (Abre em uma nova janela)' %></li>
<li><%= link_to 'Github', 'https://github.com/teresinahc/peba',  target: '_blank', title: 'Repositório no Github (Abre em uma nova janela)' %></li>
<li><%= link_to 'Feedback', 'http://teresinahc.org/peba-feedback/', target: '_blank', title: 'Página para envio de Feedback (Abre em uma nova janela)' %></li>

app/views/partials/_footer.html.erb
<% cache do %>
<footer>
  <div class='body'>
    <div class='container'>

      <div class='row'>

        <% if(current_page?(root_path)) %>
          <div class='col-md-2 col-sm-6'></div>
        <% else %>
          <div class='col-md-5 col-sm-6 clearfix search'>
            <%= render partial: 'partials/search_form'  %>
            <%= link_to('Cavada Aleatória', aleatorio_path, class: 'btn btn-default btn-sm') %>
          </div>
        <% end %>


        <div class='col-md-3 col-sm-6 clearfix'>
          <h4>Menu</h4>
          <ul>
            <%= render partial: 'partials/common_links' %>
          </ul>
        </div>

        <div class='col-md-3 col-sm-6 clearfix social'>
          <h4>Junte-se a nós</h4>
          <iframe
            src="https://ghbtns.com/github-btn.html?user=teresinahc&repo=peba&type=fork&count=true"
            frameborder="0"
            scrolling="0"
            width="170px"
            height="20px">
          </iframe>

          <%= render partial: 'partials/social', locals: {url: root_url, description: app_description } %>
        </div>

        <div class='col-md-1 col-sm-6 clearfix'>
          <h4>Realização</h4>
          <%= link_to(image_tag('teresinahc.png', width: 80), 'http://teresinahc.org', title: 'Teresina Hacker Club') %>
        </div>

      </div>
    </div>
  </div>
</footer>

<% end %>

app/views/partials/_navbar.html.erb
<% cache do %>

<nav class='navbar navbar-default hidden-xs hidden-sm'>
  <div class='container'>
    <div class='navbar-header'>
      <a class='navbar-brand' href='<%= root_path %>'>
        <%= image_tag 'peba_logo_navbar.png', alt: 'Peba' %>
      </a>
    </div>

    <div class='collapse navbar-collapse'>
      <ul class='nav navbar-nav'>
        <%= render partial: 'partials/common_links' %>
      </ul>

      <div class='nav navbar-form navbar-right'>
        <% if(current_page?(root_path)) %>

          <div class='social'>
            <%= render(
                partial: 'partials/social',
                locals: { url: @opengraph[:url], description: @opengraph[:description] }
              )
            %>
          </div>

        <% else %>
          <%= link_to('Continue Cavando', aleatorio_path, class: 'btn btn-default btn-sm') %>
        <% end %>
      </div>

    </div>
  </div>
</nav>

<% end %>

app/views/partials/_opengraph_tags.html.erb
<meta property="og:title"        content="<%= @opengraph[:title] %>" />
<meta property="og:type"         content="<%= @opengraph[:type] %>" />
<meta property="og:url"          content="<%= @opengraph[:url] %>" />
<meta property="og:image"        content="<%= @opengraph[:image] %>" />
<meta property="og:site_name"    content="<%= @opengraph[:site_name] %>" />
<meta property="og:description"  content="<%= @opengraph[:description] %>" />

app/views/partials/_search_cover.html.erb
<div class='jumbotron'>
  <div class="container">

    <div class="row">
      <div class="center-block">
        <% unless(current_page?(controller: 'deputados', action: :index)) %>
          <div id="logo" >
            <a href="<%= root_path %>" >
              <%= image_tag 'peba_logo.png' %>
            </a>
          </div>
        <% end %>

        <div id="search-form" class="peba-search col-lg-8 col-sm-10">
          <%= render 'partials/search_form' %>
        </div>
      </div>
    </div>

    <% unless(current_page?(controller: 'deputados', action: :index)) %>
      <div class="row" >
        <div id="info" class="col-lg-12" >
          <a href="<%= aleatorio_path %>" class="btn btn-default" accesskey="a">
            Cavada Aleatória
          </a>
        </div>
      </div>
    <% end %>

  </div>
</div>

app/views/partials/_search_form.html.erb
<%= form_tag deputados_path, method: 'get', enforce_utf8: false do %>
  <div class="form-group" >
    <div class="input-group">
      <%= text_field_tag :q, params[:q],
        {
          class: 'form-control',
          placeholder: 'Procure por um deputado',
          autocomplete: 'off',
          autofocus: current_page?(root_path)
        }
      %>

      <span class="input-group-btn">
        <button class="btn btn-default" type="submit" title="Iniciar uma busca">Cavar</button>
      </span>
    </div>
    <span class="help-block">Busque por nome, partido, estado, fornecedor, CPF, CNPJ... </span>
  </div>
<% end %>

app/views/partials/_social.html.erb
<iframe src="//www.facebook.com/plugins/like.php?href=<%= url %>&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=false&amp;height=21&amp;appId=379390102214515" scrolling="no" frameborder="0" allowTransparency="true" class="facebook-like-button"></iframe>

<a class="twitter-share-button"
  href="https://twitter.com/share"
  data-url="<%= url %>"
  data-via="tocadopeba">
  Tweet
</a>

<a href="whatsapp://send"
  data-text="<%= description %>"
  data-href="<%= url %>"
  class="wa_btn wa_btn_s"
  style="display:none">
  Compartilhar
</a>

app/views/sitemap/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>

<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc><%= root_url %></loc>
    <lastmod><%= Time.now.strftime('%Y-%m-%d') %></lastmod>
    <changefreq>weekly</changefreq>
    <priority>1</priority>
  </url>

  <% @politicos.each do |politico| %>
    <url>
      <loc><%= deputado_url(politico) %></loc>
      <lastmod><%= politico.updated_at.strftime('%Y-%m-%d') %></lastmod>
      <changefreq>weekly</changefreq>
      <priority>0.8</priority>
    </url>
  <% end %>
</urlset>